# Generated by Django 4.0.3 on 2022-04-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('headimg', models.ImageField(default='default/TooLazyToChangeImage.png', upload_to='headimages/')),
                ('personalSign', models.TextField(default='这个人太懒了，什么也没有留下', max_length=500)),
            ],
        ),
    ]
